/* Generated By:JavaCC: Do not edit this line. UATokenizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UATokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int CHAR = 5;
  /** RegularExpression Id. */
  int PICTURES = 6;
  /** RegularExpression Id. */
  int FILLERWORDS = 7;
  /** RegularExpression Id. */
  int THREELETTERWORDS = 8;
  /** RegularExpression Id. */
  int EMAIL = 9;
  /** RegularExpression Id. */
  int PRICES = 10;
  /** RegularExpression Id. */
  int DOMAIN = 11;
  /** RegularExpression Id. */
  int PHONE = 12;
  /** RegularExpression Id. */
  int PHONE2 = 13;
  /** RegularExpression Id. */
  int PHONE3 = 14;
  /** RegularExpression Id. */
  int WORD = 15;
  /** RegularExpression Id. */
  int HTML = 16;
  /** RegularExpression Id. */
  int HTML2 = 17;
  /** RegularExpression Id. */
  int HTMLCOMMENTS = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int TOPLEVELDOMAINS = 20;
  /** RegularExpression Id. */
  int SYMBOLS = 21;
  /** RegularExpression Id. */
  int OTHER = 22;
  /** RegularExpression Id. */
  int CHARACTERS = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<CHAR>",
    "<PICTURES>",
    "<FILLERWORDS>",
    "<THREELETTERWORDS>",
    "<EMAIL>",
    "<PRICES>",
    "<DOMAIN>",
    "<PHONE>",
    "<PHONE2>",
    "<PHONE3>",
    "<WORD>",
    "<HTML>",
    "<HTML2>",
    "<HTMLCOMMENTS>",
    "<NUMBER>",
    "<TOPLEVELDOMAINS>",
    "<SYMBOLS>",
    "<OTHER>",
    "<CHARACTERS>",
  };

}
